title: TabMed Blog
description: A blog written by Tableau consultants for healthcare users.
show_downloads: false
google_analytics:
baseurl: /blog
permalink: /:categories/:year/:month/:day/:title:output_ext
plugins_dir: _plugins
destination: ./docs